dOrgTech/homebase-app

src/modules/daocreator/hooks/useDeployer.ts
src/modules/daocreator/state/context.tsx
src/modules/daocreator/state/types.ts
src/modules/daocreator/state/utils.ts
src/modules/daocreator/steps/DaoSettings.tsx
src/modules/daocreator/steps/Governance.tsx
src/modules/daocreator/steps/TokenSettings.tsx
src/modules/daocreator/utils.ts
src/modules/daoexplorer/pages/List.tsx
src/services/contracts/baseDAO/treasuryDAO/deploy.ts

…eployment when metadata address has not been passed

Chore: Deployment improved

---

src/App.tsx
src/modules/common/Toolbar.tsx
src/modules/creator/index.tsx
src/services/beacon/context.tsx
src/services/beacon/hooks/useTezos.ts

Account menu for login and address copy

---

src/modules/common/Toolbar.tsx
src/modules/explorer/pages/List.tsx

Fix warnings

---

.github/workflows/ci.yaml
package.json

Setup continuous integration

---

src/modules/creator/steps/SelectTemplate.tsx

Update template descriptions

---

README.md
src/modules/explorer/pages/DAO.tsx

Rename Flush operation to Execute at user facing level to be more intuitive

---

src/modules/creator/components/DeploymentLoader.tsx
src/modules/explorer/pages/Proposals.tsx
src/services/contracts/metadataCarrier/deploy.ts

Improve deployment failure handling

---

src/modules/creator/steps/Governance.tsx

Display missing validation errors on stake to propose

---

src/modules/common/Toolbar.tsx

Navbar mobile screen with new styling

---

src/modules/explorer/Treasury/components/NewTreasuryProposalDialog.tsx

Dao balance added

---

src/App.tsx
src/modules/explorer/components/AppTabBar.tsx
src/modules/explorer/pages/List.tsx
src/modules/explorer/utils/FormatNumber.ts
src/services/contracts/baseDAO/hooks/useCacheDAOs.ts
src/services/contracts/baseDAO/hooks/useRegistryPropose.ts
src/services/contracts/baseDAO/hooks/useTreasuryPropose.ts
src/services/contracts/baseDAO/hooks/useVote.ts
src/services/contracts/utils.ts

Cache previously accessed dao

---

src/modules/explorer/Registry/components/UpdateRegistryDialog.tsx
src/modules/explorer/Treasury/components/NewTreasuryProposalDialog.tsx
src/modules/explorer/components/ProposalTextContainer.tsx

Add proposal title UI to proposal dialogs

---

src/modules/explorer/pages/DAO.tsx
src/modules/explorer/pages/Proposals.tsx
src/services/bakingBad/storage/types.ts
src/services/contracts/baseDAO/registryDAO/index.ts
src/services/contracts/baseDAO/treasuryDAO/index.ts

Prevent the user from flushing/executing unless there are proposals to flush/execute

---

src/modules/common/Toolbar.tsx
src/modules/common/hooks/useTotalSupply.ts
src/modules/creator/steps/DaoSettings.tsx
src/modules/creator/steps/Governance.tsx
src/modules/creator/steps/Summary.tsx
src/modules/creator/steps/TokenSettings.tsx
src/modules/creator/utils.ts
src/services/contracts/baseDAO/hooks/useDAOs.ts

Total supply calculated earlier

---

src/modules/explorer/components/ProposalDetails.tsx

Percentage fixed

---

src/modules/explorer/components/ProposalStatusHistory.tsx

tooltip added

---

src/modules/common/Blockie.tsx
src/modules/explorer/components/TokenHolders/TableRow.tsx

Fixed text wrapping on token holders table

---

src/services/bakingBad/ledger/mappers.ts

Addresses are not lowercased anymore

---

src/modules/explorer/components/ProgressBar.tsx
src/modules/explorer/components/VotersDialog.tsx
src/modules/explorer/components/VotersProgress.tsx

Made multicolor progress bar. Fixed styling and formatting

---

src/modules/creator/state/context.tsx
src/modules/creator/steps/Quorum.tsx
src/modules/explorer/components/FreezeDialog.tsx
src/modules/explorer/components/ProposalDetails.tsx
src/modules/explorer/components/ProposalForm/registryProposalForm.tsx
src/modules/explorer/components/ProposalForm/treasuryProposalForm.tsx
src/modules/explorer/components/SendXTZDialog.tsx
src/modules/explorer/components/VoteDialog.tsx
src/modules/explorer/pages/DAO.tsx
src/modules/explorer/pages/Proposals.tsx
src/services/beacon/hooks/useTezos.ts
src/services/contracts/baseDAO/hooks/useDropProposal.ts
src/services/contracts/baseDAO/hooks/useFlush.ts
src/services/contracts/baseDAO/hooks/useFreeze.ts
src/services/contracts/baseDAO/hooks/useOriginate.ts
src/services/contracts/baseDAO/hooks/useRegistryPropose.ts
src/services/contracts/baseDAO/hooks/useSendXTZ.ts
src/services/contracts/baseDAO/hooks/useTreasuryPropose.ts
src/services/contracts/baseDAO/hooks/useVote.ts
src/services/contracts/utils.ts

Related to #197
Fixed:
- Connect if not connected when invoking mutations
- Further form validation in the creator for the quorum tab

Fixed Deployment crashes

---

src/modules/creator/state/context.tsx
src/modules/creator/state/types.ts
src/modules/creator/steps/Governance.tsx
src/modules/creator/steps/Summary.tsx
src/modules/explorer/components/ConfigProposalForm.tsx
src/modules/explorer/components/GuardianChangeProposalForm.tsx
src/modules/explorer/components/GuardianTransferBadge.tsx
src/modules/explorer/components/ProposalSelectionMenu.tsx
src/modules/explorer/pages/DAO/index.tsx
src/modules/explorer/pages/ProposalDetails/index.tsx
src/modules/explorer/pages/Proposals/index.tsx
src/services/baseDAODocker/mappers.ts
src/services/contracts/baseDAO/class.ts
src/services/contracts/baseDAO/hooks/useFlush.ts
src/services/contracts/baseDAO/registryDAO/index.ts
src/services/contracts/baseDAO/registryDAO/types.ts
src/services/contracts/baseDAO/treasuryDAO/index.ts
src/services/contracts/baseDAO/types.ts
src/services/contracts/baseDAO/utils.ts
src/services/indexer/dao/hooks/useProposals.ts
src/services/indexer/dao/mappers/proposal/types.ts
src/services/indexer/dao/services.ts
src/services/indexer/types.ts

Implement Guardian Change Proposal

---

src/App.tsx
src/modules/common/Markdown.tsx
src/modules/home/FAQ.tsx
src/modules/home/FAQItem.tsx
src/modules/home/utils/faq.md

#267 
- Addressing QA comments

Fixes Issues after FAQ QA

---

src/services/beacon/context.tsx

Fix UnconfiguredSignerError error

---

src/modules/explorer/components/ConfigProposalForm.tsx
src/modules/explorer/pages/ProposalDetails/index.tsx
src/services/contracts/baseDAO/class.ts

Fixes decimal bug fix in the proposal fee change and
also incorrect Return proposal fee percentage in the proposal
detail page

Proposal Configuration Bug Fixes

---

src/modules/explorer/components/ConfigProposalForm.tsx
src/services/contracts/baseDAO/class.ts
src/services/contracts/baseDAO/types.ts

Add int conversion of proposal fee bug fix

---

src/services/bakingBad/index.ts

Change better call api url

---

src/services/bakingBad/index.ts

Fix better call API issue

---

src/modules/explorer/components/ConfigProposalFormLambda.tsx
src/modules/explorer/components/ProposalFormInput.tsx
src/modules/explorer/components/ProposalSelectionMenuLambda.tsx
src/modules/explorer/components/ResponsiveDialog.tsx
src/modules/explorer/pages/Treasury/index.tsx
src/services/bakingBad/lambdas/constants.ts
src/services/bakingBad/lambdas/index.ts

- Fixes Layouts and Scrolling on Add / Remove / Execute Lambda Modals
- Separates supported execute lambda proposals from custom created execute proposals in selection menu
- Allows opening of supported execute proposals UI from selection menu
- Code cleanups and refactors

Fix Lambda Add / Remove / Execute

---

src/modules/creator/steps/Governance.tsx
src/services/bakingBad/index.ts
src/services/bakingBad/stats/index.ts
src/services/bakingBad/stats/types.ts
src/services/bakingBad/tokenBalances/index.ts
src/services/bakingBad/tokenBalances/types.ts
src/services/bakingBad/transfers/index.ts
src/services/bakingBad/transfers/types.ts
src/services/contracts/baseDAO/hooks/useTransfers.ts
src/services/indexer/dao/hooks/useDAO.ts

Switch from BCD/tzstats to TZKT

Switch from BCD/tzstats to TZKT for V1 branch

---

src/modules/common/BackButton.tsx
src/modules/explorer/components/ConfigProposalFormLambda.tsx
src/modules/explorer/components/ProposalFormInput.tsx
src/modules/explorer/components/ProposalSelectionMenuLambda.tsx
src/modules/explorer/components/ResponsiveDialog.tsx

- Added back button to new proposal modal when on execute menu context
- Added implementation search to custom execute proposal, fixed styles

Issue/353 Part 2

---

.github/ISSUE_TEMPLATE/issue.md
src/modules/explorer/components/DAOStatsRow.tsx
src/modules/explorer/components/FreezeDialog.tsx
src/modules/explorer/components/UserBalances.tsx
src/modules/explorer/pages/DAO/index.tsx
src/modules/explorer/pages/Treasury/components/BalancesTable.tsx
src/modules/explorer/pages/Treasury/components/TransfersTable.tsx
src/services/bakingBad/tokenBalances/index.ts
src/services/bakingBad/tokenBalances/types.ts

- [Added Developer Docs section to readme](https://github.com/dOrgTech/homebase-app/commit/7ae1d52d6d029bc601fbd04eb25404721d38ed51)
- [Fix Max button for deposit, withdraw and rounding places (](https://github.com/dOrgTech/homebase-app/commit/d6b9119036dc982742385eb0c37b1ae68a23db46)https://github.com/dOrgTech/homebase-app/pull/365[)](https://github.com/dOrgTech/homebase-app/commit/d6b9119036dc982742385eb0c37b1ae68a23db46)

Release v2.2

---

src/modules/explorer/components/ConfigProposalForm.tsx
src/modules/explorer/components/DelegationChangeProposalForm.tsx
src/modules/explorer/components/GuardianChangeProposalForm.tsx
src/modules/explorer/components/NFTTransfer.tsx
src/modules/explorer/pages/NFTs/index.tsx
src/services/bakingBad/tokenBalances/index.ts
src/services/bakingBad/tokenBalances/types.ts
src/services/contracts/baseDAO/hooks/useDAOHoldings.ts

Fix Token balances not loading issue

---

src/modules/explorer/components/ConfigProposalForm.tsx
src/modules/explorer/components/DelegationChangeProposalForm.tsx
src/modules/explorer/components/GuardianChangeProposalForm.tsx
src/modules/explorer/components/NFTTransfer.tsx
src/modules/explorer/pages/NFTs/index.tsx
src/services/bakingBad/tokenBalances/index.ts
src/services/bakingBad/tokenBalances/types.ts
src/services/contracts/baseDAO/hooks/useDAOHoldings.ts

Co-authored-by: Andrei Taranu <astmobronsita@gmail.com>

Merge Develop to Master

---

src/services/bakingBad/stats/index.ts
src/services/baseDAODocker/index.ts
src/services/baseDAODocker/mappers.ts
src/services/contracts/baseDAO/class.ts

Change the start_level of DAO as per Serokell Team's suggestion

---

src/modules/explorer/pages/Proposals/index.tsx

Enable Proposal shouldDisable check

---

src/modules/creator/steps/DaoSettings.tsx

https://github.com/tezos-commons/baseDAO/blob/master/docs/specification.md#role-reassigning-functions

Remove administrator field and set current account as admin

---

src/modules/explorer/components/NewTreasuryProposalDialog.tsx
src/modules/explorer/components/ProposalForm.tsx
src/modules/explorer/components/ProposalSelectionMenuLambda.tsx
src/modules/explorer/pages/DAO/index.tsx
src/modules/explorer/pages/DAOList/index.tsx
src/modules/explorer/pages/Proposals/index.tsx
src/modules/explorer/pages/Treasury/index.tsx

Closes #386 & #440 
Closes #433

Explorer UI updates

---

src/modules/explorer/components/NewTreasuryProposalDialog.tsx
src/modules/explorer/components/ProposalForm.tsx
src/modules/explorer/pages/DAO/index.tsx
src/modules/explorer/pages/Proposals/index.tsx
src/modules/explorer/pages/Treasury/index.tsx

* Remove tabs from proposal modal & keep each modal form in its own page
* remove UI elements on Home & Proposal tabs
* added transfer funds modal validations

Merge v2-develop to v2

---

src/services/beacon/context.tsx
src/services/beacon/utils.ts

Fixes https://github.com/dOrgTech/homebase-app/issues/467

V2 - Add preferred network to beacon wallet settings

---

src/services/beacon/context.tsx
src/services/beacon/utils.ts

Fixes https://github.com/dOrgTech/homebase-app/issues/467

Add preferred network to beacon wallet settings

---

src/modules/creator/steps/Governance.tsx

Remove proposal cycle constraints from the DAO creator form

---

src/modules/explorer/hooks/useCanDropProposal.ts
src/modules/explorer/pages/ProposalDetails/index.tsx
src/modules/explorer/pages/Proposals/index.tsx
src/modules/explorer/pages/User/index.tsx
src/services/contracts/baseDAO/class.ts
src/services/contracts/baseDAO/hooks/useUnstakeFromAllProposals.ts
src/services/indexer/dao/mappers/proposal/types.ts
src/services/indexer/dao/queries.ts
src/services/indexer/types.ts

Closes https://github.com/dOrgTech/homebase-app/issues/358

Add Unstake from all proposals button

---

src/modules/explorer/pages/DAOList/index.tsx

filter search fixed for mainnet

---

src/modules/creator/index.tsx
src/modules/explorer/components/FreezeDialog.tsx
src/modules/explorer/components/NavigationMenu.tsx
src/modules/explorer/components/ProposalForm.tsx
src/modules/explorer/components/ProposalSelectionMenu.tsx
src/modules/explorer/pages/DAOList/components/DAOItem.tsx
src/modules/explorer/pages/DAOList/index.tsx
src/modules/explorer/pages/Treasury/index.tsx

Closes #568 
(hover)
(on click)
(Change tab with swap button)

fix multiple visual bugs from the merge

---

src/modules/common/MainButton.tsx
src/modules/common/SmallButton.tsx
src/modules/explorer/components/BatchBar.tsx
src/modules/explorer/components/ConfigProposalForm.tsx
src/modules/explorer/components/DelegationChangeProposalForm.tsx
src/modules/explorer/components/GuardianChangeProposalForm.tsx
src/modules/explorer/components/NewTreasuryProposalDialog.tsx
src/modules/explorer/components/ProposalForm.tsx
src/modules/explorer/components/ProposalFormInput.tsx
src/modules/explorer/components/ProposalFormSendButton.tsx
src/modules/explorer/components/ResponsiveDialog.tsx
src/modules/explorer/pages/DAOList/index.tsx
src/modules/explorer/pages/Proposals/index.tsx
src/theme/index.ts

All Homebase modals updated

---

src/modules/common/ChangeNetworkButton.tsx
src/modules/creator/deployment/steps/Distribution.tsx
src/modules/creator/deployment/steps/Summary.tsx
src/modules/explorer/components/ChangeNetworkButton.tsx
src/modules/explorer/components/NetworkSheet.tsx
src/modules/explorer/components/Toolbar.tsx
src/modules/lite/explorer/components/ChangeNetworkButton.tsx
src/services/beacon/hooks/useTezos.ts
src/services/beacon/utils.ts
src/services/contracts/baseDAO/hooks/useOriginate.ts
src/services/contracts/token/hooks/useToken.ts
src/services/contracts/token/index.ts
src/services/services/lite/lite-services.ts

- https://app.zenhub.com/workspaces/tezos-homebase-63238426ddf385159a4c4b12/issues/gh/dorgtech/homebase-app/606
- https://app.zenhub.com/workspaces/tezos-homebase-63238426ddf385159a4c4b12/issues/gh/dorgtech/homebase-app/598
- Network Switching error

Bug Fixes and Improvements

---

src/modules/explorer/pages/Proposals/index.tsx
src/modules/lite/explorer/components/ProposalList.tsx
src/modules/lite/explorer/components/ProposalTableRow.tsx
src/modules/lite/explorer/pages/ProposalDetails/index.tsx

user who has delegated cant vote

---

package.json
src/modules/lite/explorer/pages/CreateProposal/index.tsx
yarn.lock

Added validation for link

---

src/modules/explorer/pages/User/components/DelegationBanner.tsx
src/modules/explorer/pages/User/components/DelegationModal.tsx
src/services/contracts/token/hooks/useTokenDelegate.ts

Delegation modal updated - Status refetch working

---

src/models/Community.ts
src/modules/explorer/pages/DAOList/components/DAOItem.tsx
src/modules/explorer/pages/DAOList/index.tsx
src/modules/lite/creator/index.tsx
src/modules/lite/explorer/components/DaoCardDetail.tsx
src/modules/lite/explorer/hooks/useHolderTotalCount.tsx
src/modules/lite/explorer/pages/CommunityDetails/index.tsx
src/services/lite/utils.ts
src/services/services/lite/lite-services.ts
src/services/services/types.ts

Closes #606 
Note: Needs backend PR approved first

Connection with backend new endpoints

---

src/modules/explorer/pages/ProposalDetails/index.tsx
src/modules/lite/explorer/components/ChoiceItemSelected.tsx
src/modules/lite/explorer/components/ProposalDetailCard.tsx
src/modules/lite/explorer/components/VoteDetails.tsx

Fix poll options

---

src/modules/lite/explorer/components/DaoCardDetail.tsx

link to terms added

---

src/modules/lite/explorer/pages/ProposalDetails/index.tsx

deeplink fixed

---

src/modules/common/Footer.tsx

update footer design

---

src/modules/common/ChangeNetworkButton.tsx
src/modules/creator/steps/Quorum.tsx

Fixed quorum slider

---

src/modules/lite/explorer/components/VoteDetails.tsx
src/services/lite/utils.ts

Fix XTZ weight to be determined by user balance and total XTZ voted, instead of total voters.
Attempts to address: https://github.com/dOrgTech/homebase-app/issues/800

Fix XTZ weight

---

src/modules/explorer/pages/DAOList/components/DAOItem.tsx

Fix card padding

---

src/modules/explorer/components/NavigationMenu.tsx
src/modules/explorer/components/UsersTable.tsx
src/modules/explorer/pages/DAO/index.tsx
src/theme/index.ts

top members component brought back

---

src/modules/explorer/pages/ProposalDetails/index.tsx

Fix for XTZ

---

.gitignore
src/App.tsx
src/modules/explorer/context/HistoryLength/index.tsx
src/modules/lite/explorer/pages/ProposalDetails/index.tsx

Fixes #856 
To fix the issue, we are counting the items in the history stack from the time the site is loaded. There was no direct way to implement this directly with `react-router-dom`

Fix for Back to community 
